#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH -N 1 # Ensure that all cores are on one machine
#SBATCH -D /home/group07/code/MCV-M5-Team7/week3 # working directory
#SBATCH -p mhigh # Partition to submit to
#SBATCH --mem 4096 # 4GB memory
#SBATCH --gres gpu:1 # Request of 1 gpu
#SBATCH -o runout/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e runout/%x_%u_%j.err # File to which STDERR will be written
python demo.py
